server:
  port: 8761

spring:
  application:
    name: service-discovery

eureka:
  client:
    register-with-eureka: false # This instance will not register itself
    fetch-registry: false # This instance will not fetch registry