
server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:////Users/yeongwoonshin/Desktop/Work/git-local-repo
          default-label: master