server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: git
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/Work/native-file-repo
        git: #default
          uri: https://github.com/joneconsulting/spring-cloud-config
          default-label: master
#          username: [username]
#          password: [password]

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - beans
          - info
          - busrefresh