
server:
  port: 8000

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/order-service/**
            - id: catalog-service
              uri: lb://CATALOG-SERVICE
              predicates:
                - Path=/catalog-service/**
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/**
            - id: first-service
              #uri: http://localhost:8081
              uri: lb://MY-FIRST-SERVICE
              predicates:
                - Path=/first-service/**
              filters:
                #- AddRequestHeader=f-request,hello request
                #- AddResponseHeader=f-response,hello response
                - CustomFilter
            - id : second-service
              #uri: http://localhost:8082
              uri: lb://MY-SECOND-SERVICE
              predicates:
                - Path=/second-service/**
              filters:
                  #- AddRequestHeader=s-request,hello request
                  #- AddResponseHeader=s-response,hello response
                  - CustomFilter
                  - name : LoggingFilter
                    args:
                      baseMessage: "Logging Filter for second service"
                      preLogger: true
                      postLogger: true
          default-filters:
            - name: GlobalFilter
              args:
                baseMessage: "This is a global filter"
                preLogger: true
                postLogger: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/